services:
  app:
    build: .
    ports:
      - "8082:8080" # <-- ALTERADO AQUI (A porta externa agora é 8082)
    environment:
      - SPRING_APPLICATION_NAME=claricejoias-ws
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=claricejoias
    depends_on:
      - minio

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: claricejoias
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  evolution-api:
    image: atendai/evolution-api:latest
    ports:
      - "8081:8080"
    environment:
      - SERVER_URL=http://localhost:8081
      - AUTHENTICATION_API_KEY=claricejoias
      # Banco de Dados
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://postgres:admin@db:5432/claricejoias?schema=public
      - DATABASE_CONNECTION_CLIENT_NAME=evolution
      # Desativar dependências externas para evitar Timed Out
      - CACHE_REDIS_ENABLED=false
      - CACHE_LOCAL_ENABLED=true
      - RABBITMQ_ENABLED=false
      - SQS_ENABLED=false
    depends_on:
      - db
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  db_data:
  evolution_instances: