services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=claricejoias-ws
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=claricejoias
    depends_on:
      - minio

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: claricejoias
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Persistência dos dados

volumes:
  db_data: