spring.application.name=claricejoias-ws


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/claricejoias}
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=${MINIO_BUCKET_NAME:claricejoias}



spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


api.url.front=http://localhost:3000,https://www.claricejoiasoficial.com.br,https://claricejoiasoficial.com.br


spring.batch.jdbc.initialize-schema=always


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8083/realms/claricejoias
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8083/realms/claricejoias/protocol/openid-connect/certs


keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:8083}


app.whatsapp.cooldown-horas=24
evolution.api.url=${EVOLUTION_API_URL:http://localhost:8081}
evolution.api.key=claricejoias
evolution.api.instance=claricejoias

logging.level.org.springframework.security=TRACE