spring.application.name=claricejoias-ws

spring.datasource.url=jdbc:postgresql://localhost:5433/claricejoias
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=claricejoias

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

api.url.front=http://localhost:3000,https://www.claricejoiasoficial.com.br,https://claricejoiasoficial.com.br

# Inicializa as tabelas internas do Spring Batch
spring.batch.jdbc.initialize-schema=always

# O link deve apontar para o realm que voce criou
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8083/realms/claricejoias
# Isso ajuda o Spring a baixar as chaves publicas para validar a assinatura do JWT automaticamente
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8083/realms/claricejoias/protocol/openid-connect/certs

app.whatsapp.cooldown-horas=24

evolution.api.url=http://localhost:8081
evolution.api.key=claricejoias
evolution.api.instance=claricejoias